-- ============================================================
-- CARRIER & WAREHOUSE PERFORMANCE
-- ============================================================

-- 41. Total Orders by Carrier
SELECT
    Carrier,
    COUNT(*) AS Total_Orders
FROM Orders
GROUP BY Carrier
ORDER BY Total_Orders DESC;

------------------------------------------------------------

-- 42. Revenue Generated by Carrier
SELECT
    Carrier,
    ROUND(SUM(Invoice_Amount),2) AS Revenue
FROM Orders
GROUP BY Carrier
ORDER BY Revenue DESC;

------------------------------------------------------------

-- 43. Average Shipping Cost by Carrier
SELECT
    Carrier,
    ROUND(AVG(Shipping_Cost),2) AS Avg_Shipping_Cost
FROM Orders
GROUP BY Carrier
ORDER BY Avg_Shipping_Cost DESC;

------------------------------------------------------------

-- 44. Total Orders Processed by Warehouse
SELECT
    Warehouse_Name,
    COUNT(*) AS Total_Orders
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Total_Orders DESC;

------------------------------------------------------------

-- 45. Revenue Handled by Warehouse
SELECT
    Warehouse_Name,
    ROUND(SUM(Invoice_Amount),2) AS Revenue
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Revenue DESC;

------------------------------------------------------------

-- 46. Average Warehouse Utilization
SELECT
    Warehouse_Name,
    ROUND(AVG(Warehouse_Utilization_Percentage),2) AS Avg_Utilization
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Avg_Utilization DESC;

------------------------------------------------------------

-- 47. Average Profit Margin by Warehouse
SELECT
    Warehouse_Name,
    ROUND(AVG(Profit_Margin_Percentage),2) AS Avg_Profit_Margin
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Avg_Profit_Margin DESC;

------------------------------------------------------------

-- 48. Warehouse-wise Shipping Cost
SELECT
    Warehouse_Name,
    ROUND(AVG(Shipping_Cost),2) AS Avg_Shipping_Cost
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Avg_Shipping_Cost DESC;

------------------------------------------------------------

-- 49. Carrier-wise Profit Margin
SELECT
    Carrier,
    ROUND(AVG(Profit_Margin_Percentage),2) AS Avg_Profit_Margin
FROM Orders
GROUP BY Carrier
ORDER BY Avg_Profit_Margin DESC;

------------------------------------------------------------

-- 50. Warehouse-wise Customer Satisfaction
SELECT
    Warehouse_Name,
    ROUND(AVG(CSAT_Score),2) AS Avg_CSAT
FROM Orders
GROUP BY Warehouse_Name
ORDER BY Avg_CSAT DESC;